framework:
  website: aspectran.com
  version: 9.2.1

  build:
    - mvn clean package

  files:
    - config

  binaries:
    - target/benchmark-jar-with-dependencies.jar

  command: /usr/bin/java -Daspectran.profiles.active=benchmark -jar /opt/web/target/benchmark-jar-with-dependencies.jar /opt/web /config/aspectran-config.apon
