framework:
  website: aspectran.com
  version: 9.1.2-SNAPSHOT

  build:
    - mvn clean package

  files:
    - aspectran-config.apon

  binaries:
    - target/benchmark-jar-with-dependencies.jar

  command: /usr/bin/java -jar /opt/web/target/benchmark-jar-with-dependencies.jar /opt/web/aspectran-config.apon